### ISSUE TITLE
Fetch type alias

### ISSUE THREAD

**Issue by mitchellwrosen** [ElvishJerricco/fraxl#2]
I just watched your Haskell meetup video and am peeking around the codebase a bit. Very interesting stuff!

Just curious, why is Fetch given as

``` haskell
type Fetch f m a = ASeq f a -> m (ASeq m a)
```

rather than

``` haskell
type Fetch f m a = ASeq f a -> m (ASeq Identity a)
```

Does only asking the interpretation function to put together a sequence of `m a` actions unlock some additional power, versus just executing the actions right then? It seems the actions are just `join`ed away by `runFraxl` in the end anyways.

Thanks!

**Comment by ElvishJerricco** [comment]
These actions that are returned are what I call "wait actions". Fetch returns them because if it adds a level of asynchronous-ness. If a batch of fetches were synchronous, then Fraxl couldn't run multiple data sources at the same time. This way, every data source can return wait actions so that all their threads can go at the same time, and Fraxl just needs to call the whole group of wait actions (via join) to wait on all of them

**Comment by mitchellwrosen** [comment]
Oh, yeah, that makes sense.
